// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8PqxDt9cA9f2PIlqn9NyfEN9LfbZf6-U',
    appId: '1:160975139312:web:157e96e9378a6ee3d8ad35',
    messagingSenderId: '160975139312',
    projectId: 'myproject-77e36',
    authDomain: 'myproject-77e36.firebaseapp.com',
    storageBucket: 'myproject-77e36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS9Z6TlzjtJ_AEbgV_q4zMoeo8YnN9Xgw',
    appId: '1:160975139312:android:f911e3d9a2040c71d8ad35',
    messagingSenderId: '160975139312',
    projectId: 'myproject-77e36',
    storageBucket: 'myproject-77e36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNdDEY6tHbXEQXABZTK5hMEYMuzXeXl7Q',
    appId: '1:160975139312:ios:adbebd1e6fa9b726d8ad35',
    messagingSenderId: '160975139312',
    projectId: 'myproject-77e36',
    storageBucket: 'myproject-77e36.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNdDEY6tHbXEQXABZTK5hMEYMuzXeXl7Q',
    appId: '1:160975139312:ios:adbebd1e6fa9b726d8ad35',
    messagingSenderId: '160975139312',
    projectId: 'myproject-77e36',
    storageBucket: 'myproject-77e36.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8PqxDt9cA9f2PIlqn9NyfEN9LfbZf6-U',
    appId: '1:160975139312:web:1ff911dd5437b42dd8ad35',
    messagingSenderId: '160975139312',
    projectId: 'myproject-77e36',
    authDomain: 'myproject-77e36.firebaseapp.com',
    storageBucket: 'myproject-77e36.appspot.com',
  );
}
